/* Donde Ayudar — bilingual content + UI strings (ES / EN) */
window.DA = (function () {
  const STRINGS = {
    es: {
      // nav + chrome
      navCasos: 'Casos', navEmpleos: 'Empleos', navOrgs: 'Organizaciones', navComo: 'Cómo funciona',
      ctaPublicar: 'Publicar oportunidad', ctaAyudar: 'Quiero ayudar',
      langName: 'ES', langSwitch: 'English', themeDark: 'Modo oscuro', themeLight: 'Modo claro',
      verTodos: 'Ver todos', verCaso: 'Ver caso', verAplicar: 'Ver y aplicar', volver: 'Volver',
      verificadoPor: 'Verificado por', necesidadPrincipal: 'Necesidad principal',
      badgeDonacion: 'Donación directa', verFormas: 'Ver formas de ayuda', fConDonacion: 'Con formas de ayuda',
      formasT: 'Formas de ayudar directamente',
      formasSub: 'Estos métodos fueron compartidos por el caso u organización verificada. Donde Ayudar no procesa pagos: tu apoyo va directamente al beneficiario.',
      formasDisc: 'Donde Ayudar no procesa pagos ni retiene fondos. Los aportes se hacen directamente a los métodos compartidos por el caso u organización verificada. Antes de donar, verifica que el caso esté marcado como verificado.',
      formasPending: 'Las formas de apoyo estarán disponibles cuando este caso sea verificado.',
      formasEmpty: 'Este caso todavía no tiene métodos de apoyo publicados.',
      dmHolder: 'Beneficiario', copyBtn: 'Copiar dato', copiedMsg: '¡Copiado!',
      // hero
      heroEyebrow: 'Ayuda verificada · Empleo con propósito',
      heroT1: 'Ayuda verificada. ', heroT2: 'Oportunidades reales.',
      heroSub: 'Donde Ayudar conecta casos afectados por emergencias con organizaciones aliadas, apoyo seguro y oportunidades de empleo para reconstruir estabilidad.',
      heroCtaCasos: 'Ver casos verificados', heroCtaEmpleos: 'Ver empleos', heroCtaComo: 'Cómo funciona',
      trust1: 'Sin pagos en plataforma', trust2: 'Sin datos sensibles', trust3: 'Sin login',
      heroCardCaso: 'Caso verificado', heroCardCasoSub: 'Validado por una organización',
      heroCardOrg: 'Organización aliada', heroCardOrgSub: 'Verifica y acompaña',
      heroCardEmpleo: 'Empleo disponible', heroCardEmpleoSub: 'Remoto y presencial',
      heroCardAyuda: 'Ayuda segura', heroCardAyudaSub: 'Sin datos sensibles',
      flowAyuda: 'Ayuda', flowOrg: 'Organización', flowEmpleo: 'Empleo',
      heroPhoto: 'foto cálida — manos unidas /', heroPhoto2: 'equipo trabajando',
      protegidos: 'Datos protegidos', verifAliados: 'Verificado por aliados', verifAliadosSub: 'Cada caso pasa por una organización',
      // mensaje clave
      mensaje1: 'La ayuda inmediata resuelve el presente, ', mensaje2: 'pero el empleo puede reconstruir estabilidad.',
      // pasos
      pasosEyebrow: 'Empieza aquí', pasosH2: '¿No sabes por dónde empezar?',
      pasosLead: 'Tres formas claras de apoyar y reconstruir juntos.',
      paso1T: 'Encuentra casos verificados', paso1X: 'Explora casos reales verificados por organizaciones aliadas. Solo información pública y segura.', paso1L: 'Explorar casos',
      paso2T: 'Apoya de forma segura', paso2X: 'Ayuda directamente a una familia o persona refugiada, por canales verificados y sin exponer datos sensibles.', paso2L: 'Cómo funciona',
      paso3T: 'Conecta con oportunidades de empleo', paso3X: 'Publica o encuentra empleo remoto y presencial, verificado. Un ingreso estable transforma la ayuda en autonomía.', paso3L: 'Ver empleos',
      // casos / empleos featured
      casosEyebrow: 'Personas reales', casosH2: 'Casos recientes',
      empleosEyebrow: 'Oportunidades curadas y verificadas', empleosH2: 'Empleos disponibles',
      // trust section
      trustEyebrow: 'Confianza', trustH2: 'Ayuda segura y transparente',
      trustLead: 'Diseñado para proteger la dignidad de cada persona. Conexión, no caridad agresiva.',
      tc1T: 'Sin pagos en plataforma', tc1X: 'El dinero nunca pasa por aquí. Fluye por los canales de cada organización.',
      tc2T: 'Verificación por aliados', tc2X: 'Fundaciones y voluntarios verifican cada caso y oferta antes de publicarlos.',
      tc3T: 'Sin datos sensibles', tc3X: 'Nada de cédulas, pasaportes ni documentos privados. Solo información pública.',
      tc4T: 'Conexión, no caridad', tc4X: 'Buscamos estabilidad y dignidad a largo plazo, no dependencia.',
      discTitle: 'Cómo protegemos a las personas',
      discText: 'Donde Ayudar no almacena documentos personales ni procesa pagos. La verificación ocurre a través de organizaciones o voluntarios aliados.',
      // home CTA
      ctaEyebrow: 'Súmate', ctaH2: '¿Tu empresa contrata talento remoto o presencial?',
      ctaText: 'Publica una oferta de empleo verificada y ayuda a una familia afectada a recuperar estabilidad económica. La curación es manual y respeta la dignidad de cada persona.',
      ctaBtn1: 'Publicar una oferta', ctaBtn2: 'Cómo funciona',
      // footer
      footTag: 'Conecta ayuda. Abre oportunidades. Reconstruimos juntos.',
      footMsg: 'La ayuda inmediata resuelve el presente, pero el empleo puede reconstruir estabilidad.',
      footExplorar: 'Explorar', footParticipar: 'Participar',
      footPublicar: 'Publicar una oferta', footConectar: 'Conectar una organización', footContacto: 'Contacto',
      footLegal: 'Esta plataforma no almacena documentos personales ni procesa pagos. La verificación ocurre a través de organizaciones o voluntarios aliados.',
      footCopy: '© 2026 Donde Ayudar · Proyecto comunitario sin fines de lucro.',
      // casos page
      casosPEyebrow: 'Casos', casosPH1: 'Familias y personas afectadas',
      casosPLead: 'Cada caso es verificado por una organización o voluntario aliado. Mostramos solo información pública y segura — el contacto siempre ocurre por canales verificados.',
      casosNoticeT: 'Seguridad primero', casosNoticeX: 'No almacenamos documentos personales ni procesamos pagos. La verificación ocurre a través de organizaciones o voluntarios aliados.',
      fTodos: 'Todos', fVerificados: 'Verificados', fUrgentes: 'Urgentes', fPendientes: 'En verificación',
      stVerificado: 'Verificado', stUrgente: 'Urgente', stPendiente: 'En verificación',
      casosEmpty: 'No hay casos con este filtro. Prueba con otra categoría.',
      // empleos page
      empleosPEyebrow: 'Empleos verificados', empleosPH1: 'Empleos reales, revisados y seguros',
      empleosPLead: 'Empleos reales y verificados, remotos y presenciales. Un ingreso estable ayuda a una familia a reconstruir su estabilidad.',
      empleosNoticeT: 'Antes de aplicar', empleosNoticeX: 'Las oportunidades son curadas y verificadas manualmente. Aun así, recomendamos confirmar cada oferta antes de compartir información personal.',
      fTodas: 'Todas', fRemoto: 'Remoto', fPresencial: 'Presencial', fHibrido: 'Híbrido',
      empleosEmpty: 'No hay empleos con esta modalidad. Prueba con otra.',
      ofertaVerificada: 'Oferta verificada',
      // orgs page
      orgsPEyebrow: 'Organizaciones', orgsPH1: 'La red que hace posible el puente',
      orgsPLead: 'Fundaciones, centros de acopio, refugios y redes de voluntarios. Son ellas quienes verifican casos y garantizan que la ayuda llegue por canales de confianza.',
      areasApoyo: 'Áreas de apoyo', escribir: 'Escribir', contactar: 'Contactar', sitioWeb: 'Sitio web',
      allyLabel: 'Organización aliada', orgPendiente: 'En verificación',
      sumarseT: '¿Tu organización quiere sumarse?', sumarseX: 'Si eres una fundación, refugio o red de voluntarios y deseas verificar casos o canalizar ayuda, conéctate con nosotros.', sumarseBtn: 'Conectar organización',
      // caso detail
      cdEstado: 'Estado', cdUbicacion: 'Ubicación', cdActualizacion: 'Última actualización',
      cdResumen: 'Resumen', cdNecesidades: 'Necesidades', cdHabilidades: 'Habilidades laborales', cdDisp: 'Disponibilidad laboral',
      cdNotaT: 'Nota de seguridad', cdNotaX: 'Esta plataforma no almacena documentos personales ni procesa pagos. La verificación ocurre a través de organizaciones o voluntarios aliados.',
      cdComoApoyar: 'Cómo apoyar', cdContactoSeguro: 'Contacto seguro',
      cdApoyar: 'Apoyar este caso', cdNoSupport: 'El canal de apoyo se habilita una vez completada la verificación con la organización aliada.', cdRecruiter: '¿Eres recruiter? Ver perfiles',
      volverCasos: 'Volver a casos', volverEmpleos: 'Volver a empleos',
      // empleo detail
      edEmpresa: 'Empresa', edModalidad: 'Modalidad', edCategoria: 'Categoría', edPublicado: 'Publicado',
      edDescripcion: 'Descripción', edRequisitos: 'Requisitos', edDetalles: 'Detalles',
      edAntesT: 'Antes de compartir tus datos', edAntesX: 'Las oportunidades son curadas y verificadas manualmente. Aun así, recomendamos confirmar cada oferta antes de compartir información personal.',
      edAplicar: 'Aplicar', edFuente: 'Fuente', edAplicarBtn: 'Aplicar en sitio externo', edVerif: 'Oferta verificada por el equipo',
      // como funciona
      comoEyebrow: 'El modelo', comoH1: 'Cómo funciona',
      comoLead: 'Somos una capa pública de conexión, no una app de donaciones ni un intermediario financiero. Estos son los principios que guían cada decisión del proyecto.',
      cf1T: 'La plataforma centraliza información segura', cf1X: 'Reunimos casos, empleo remoto y presencial, y organizaciones aliadas en un solo lugar. Toda la información es pública y segura: nunca cédulas, pasaportes ni documentos privados.',
      cf2T: 'Los casos vienen de organizaciones aliadas', cf2X: 'No publicamos casos por nuestra cuenta. Cada familia o persona es identificada y verificada por una fundación, refugio o red de voluntarios aliada.',
      cf3T: 'No se almacenan documentos sensibles', cf3X: 'No hay base de datos de información personal ni login. El contacto y la verificación ocurren por canales de las organizaciones, no en esta web.',
      cf4T: 'No se procesan pagos', cf4X: 'La plataforma no recibe ni gestiona dinero. Las donaciones y el apoyo fluyen directamente por los canales verificados de cada organización.',
      cf5T: 'Las oportunidades son curadas y verificadas', cf5X: 'Nada de scraping. Cada oferta de empleo remoto o presencial se revisa y verifica manualmente antes de publicarse.',
      cf6T: 'Conectamos ayuda inmediata con estabilidad', cf6X: 'El objetivo final: que la ayuda puntual resuelva el presente y que un empleo reconstruya la estabilidad económica a largo plazo.',
      limEyebrow: 'Límites claros', limH2: 'Qué hacemos y qué no',
      siT: 'Qué SÍ hacemos', si1: 'Publicar casos verificados con información pública.', si2: 'Curar y verificar manualmente ofertas de empleo remoto y presencial.', si3: 'Conectar familias con organizaciones, donantes y recruiters.', si4: 'Mantener todo estático, seguro y simple.',
      noT: 'Qué NO hacemos', no1: 'Procesar pagos o donaciones en la plataforma.', no2: 'Guardar cédulas, pasaportes o documentos privados.', no3: 'Pedir login ni crear cuentas.', no4: 'Hacer scraping de LinkedIn, Indeed u otras plataformas.',
      compT: 'Compromiso de seguridad y dignidad', compX: 'Esta plataforma no almacena documentos personales ni procesa pagos. La verificación ocurre a través de organizaciones o voluntarios aliados. Cada caso se trata con respeto: no buscamos caridad, sino conexión, estabilidad y dignidad.',
      comoCtaEyebrow: 'Participa', comoCtaH2: 'Ayuda a convertir el presente en estabilidad', comoCtaX: 'Publica una oferta de empleo, conecta tu organización o comparte un caso verificado. Cada conexión cuenta.', comoCtaB1: 'Publicar una oferta', comoCtaB2: 'Ver casos',
      // publicar
      pubEyebrow: 'Para recruiters y cualquier persona', pubH1: 'Publica una oferta de empleo verificada',
      pubLead: 'Recruiters, empresas y aliados pueden publicar ofertas de empleo —remoto o presencial—. Revisamos y verificamos cada propuesta manualmente antes de publicarla.',
      pubJobT: 'Detalles de la oferta', pubJobSub: 'Sin servidores ni base de datos: enviamos tu propuesta y nuestro equipo la verifica manualmente antes de publicarla.',
      pubSentT: '¡Gracias! Recibimos tu propuesta', pubSentX: 'La revisaremos y verificaremos. Si es una oferta real y segura, la publicaremos como empleo verificado.',
      lTitulo: 'Título del puesto', lEmpresa: 'Empresa', lModalidad: 'Modalidad', lUbicacion: 'Ubicación (si es presencial)', lCategoria: 'Categoría', lDescripcion: 'Descripción del rol', lLink: 'Link o correo para aplicar', lCorreo: 'Tu correo de contacto',
      phTitulo: 'Ej. Asistente administrativo', phEmpresa: 'Nombre de tu empresa u organización', phUbicacion: 'Ej. La Guaira, Venezuela', phCategoria: 'Ej. Tecnología, Logística, Diseño', phDescripcion: 'Responsabilidades, requisitos clave y lo que ofrece la empresa', phCorreo: 'tu@empresa.com',
      optRemoto: 'Remoto', optPresencial: 'Presencial', optHibrido: 'Híbrido',
      pubJobBtn: 'Enviar oferta',
      pubOrgT: 'Conectar una organización', pubOrgSub: '¿Eres una fundación, refugio, centro de acopio o red de voluntarios? Súmate como aliado para verificar casos y canalizar ayuda.',
      pubOrgSentT: '¡Solicitud recibida!', pubOrgSentX: 'Te contactaremos para sumar a tu organización a la red de aliados.',
      lOrgNombre: 'Nombre de la organización', lOrgTipo: 'Tipo', lOrgAreas: 'Áreas de apoyo', lOrgContacto: 'Correo o canal de contacto',
      phOrgTipo: 'Fundación, refugio, centro de acopio…', phOrgAreas: 'Verificación, alimentos, mentoría…', phOrgContacto: 'contacto@organizacion.org',
      pubOrgBtn: 'Enviar solicitud de alianza',
      curamosT: 'Cómo verificamos', cur1: 'Recibimos tu propuesta.', cur2: 'Verificamos que sea una oferta real y segura.', cur3: 'La publicamos como empleo verificado.', cur4: 'Conectamos con perfiles afines.',
      sinBackT: 'Sin backend, sin datos sensibles', sinBackX: 'No almacenamos información en servidores ni procesamos pagos.',
      escribeDirecto: '¿Prefieres escribir directo?',
      reqAll: 'obligatorio',
      navRegistro: 'Registro',
      regEyebrow: 'Únete a Donde Ayudar', regH1: 'Crea tu cuenta',
      regLead: 'Donde Ayudar es de todos. Únete como recruiter o empresa, como organización aliada o como voluntario: publica oportunidades, verifica casos o apoya a las familias. Reconstruimos juntos.',
      regTabRecruiter: 'Soy recruiter / empresa', regTabOrg: 'Soy organización aliada', regTabPersona: 'Soy voluntario / persona',
      regRecDesc: 'Publica ofertas de empleo remotas y presenciales, verificadas por el equipo.',
      regOrgDesc: 'Verifica casos, acompaña a familias y canaliza ayuda por canales seguros.',
      regPersonaDesc: 'Comparte oportunidades, difunde casos verificados y apoya a familias afectadas. Cualquiera puede sumar.',
      regNombre: 'Nombre completo', regEmail: 'Correo electrónico', regEntidad: 'Empresa u organización (si aplica)',
      regPass: 'Contraseña', regPass2: 'Confirmar contraseña',
      regBtn: 'Crear cuenta', regSentT: '¡Cuenta creada!',
      regSentX: 'Demo sin backend: no se guardan credenciales ni datos. Ya puedes publicar una oferta o conectar tu organización.',
      regHave: '¿Ya tienes cuenta?', regLogin: 'Iniciar sesión',
      regNote: 'Plataforma de demostración: el registro es visual y no almacena datos ni contraseñas.',
      regGoPublicar: 'Publicar una oferta', regGoOrg: 'Conectar organización', regGoCasos: 'Explorar casos',
    },
    en: {
      navCasos: 'Cases', navEmpleos: 'Jobs', navOrgs: 'Organizations', navComo: 'How it works',
      ctaPublicar: 'Post an opportunity', ctaAyudar: 'I want to help',
      langName: 'EN', langSwitch: 'Español', themeDark: 'Dark mode', themeLight: 'Light mode',
      verTodos: 'View all', verCaso: 'View case', verAplicar: 'View & apply', volver: 'Back',
      verificadoPor: 'Verified by', necesidadPrincipal: 'Main need',
      badgeDonacion: 'Direct donation', verFormas: 'See ways to help', fConDonacion: 'With ways to help',
      formasT: 'Ways to help directly',
      formasSub: 'These methods were shared by the verified case or partner organization. Donde Ayudar does not process payments: your support goes directly to the beneficiary.',
      formasDisc: 'Donde Ayudar does not process payments or hold funds. Contributions are made directly to the methods shared by the verified case or organization. Before donating, make sure the case is marked as verified.',
      formasPending: 'Ways to help will be available once this case is verified.',
      formasEmpty: 'This case has no support methods published yet.',
      dmHolder: 'Beneficiary', copyBtn: 'Copy', copiedMsg: 'Copied!',
      heroEyebrow: 'Verified help · Purposeful work',
      heroT1: 'Verified help. ', heroT2: 'Real opportunities.',
      heroSub: 'Donde Ayudar connects people affected by emergencies with partner organizations, safe support and job opportunities to rebuild stability.',
      heroCtaCasos: 'View verified cases', heroCtaEmpleos: 'View jobs', heroCtaComo: 'How it works',
      trust1: 'No payments on platform', trust2: 'No sensitive data', trust3: 'No login',
      heroCardCaso: 'Verified case', heroCardCasoSub: 'Validated by an organization',
      heroCardOrg: 'Partner organization', heroCardOrgSub: 'Verifies and supports',
      heroCardEmpleo: 'Job available', heroCardEmpleoSub: 'Remote and on-site',
      heroCardAyuda: 'Safe help', heroCardAyudaSub: 'No sensitive data',
      flowAyuda: 'Help', flowOrg: 'Organization', flowEmpleo: 'Job',
      heroPhoto: 'warm photo — hands together /', heroPhoto2: 'team at work',
      protegidos: 'Data protected', verifAliados: 'Verified by allies', verifAliadosSub: 'Every case goes through an organization',
      mensaje1: 'Immediate help solves the present, ', mensaje2: 'but a job can rebuild stability.',
      pasosEyebrow: 'Start here', pasosH2: 'Not sure where to start?',
      pasosLead: 'Three clear ways to help and rebuild together.',
      paso1T: 'Find verified cases', paso1X: 'Explore real cases verified by partner organizations. Public, safe information only.', paso1L: 'Explore cases',
      paso2T: 'Support safely', paso2X: 'Help a displaced family or person directly, through verified channels and without exposing sensitive data.', paso2L: 'How it works',
      paso3T: 'Connect with job opportunities', paso3X: 'Post or find verified remote and on-site jobs. A stable income turns help into autonomy.', paso3L: 'View jobs',
      casosEyebrow: 'Real people', casosH2: 'Recent cases',
      empleosEyebrow: 'Curated and verified opportunities', empleosH2: 'Available jobs',
      trustEyebrow: 'Trust', trustH2: 'Safe and transparent help',
      trustLead: 'Designed to protect each person’s dignity. Connection, not aggressive charity.',
      tc1T: 'No payments on platform', tc1X: 'Money never passes through here. It flows through each organization’s channels.',
      tc2T: 'Verified by allies', tc2X: 'Foundations and volunteers verify every case and job before publishing.',
      tc3T: 'No sensitive data', tc3X: 'No IDs, passports or private documents. Public information only.',
      tc4T: 'Connection, not charity', tc4X: 'We seek long-term stability and dignity, not dependency.',
      discTitle: 'How we protect people',
      discText: 'Donde Ayudar does not store personal documents or process payments. Verification happens through partner organizations or volunteers.',
      ctaEyebrow: 'Join in', ctaH2: 'Does your company hire remote or on-site talent?',
      ctaText: 'Post a verified job and help an affected family recover financial stability. Curation is manual and respects each person’s dignity.',
      ctaBtn1: 'Post a job', ctaBtn2: 'How it works',
      footTag: 'Connect help. Open opportunities. We rebuild together.',
      footMsg: 'Immediate help solves the present, but a job can rebuild stability.',
      footExplorar: 'Explore', footParticipar: 'Take part',
      footPublicar: 'Post a job', footConectar: 'Connect an organization', footContacto: 'Contact',
      footLegal: 'This platform does not store personal documents or process payments. Verification happens through partner organizations or volunteers.',
      footCopy: '© 2026 Donde Ayudar · Non-profit community project.',
      casosPEyebrow: 'Cases', casosPH1: 'Affected families and people',
      casosPLead: 'Every case is verified by a partner organization or volunteer. We show only public, safe information — contact always happens through verified channels.',
      casosNoticeT: 'Safety first', casosNoticeX: 'We do not store personal documents or process payments. Verification happens through partner organizations or volunteers.',
      fTodos: 'All', fVerificados: 'Verified', fUrgentes: 'Urgent', fPendientes: 'In review',
      stVerificado: 'Verified', stUrgente: 'Urgent', stPendiente: 'In review',
      casosEmpty: 'No cases with this filter. Try another category.',
      empleosPEyebrow: 'Verified jobs', empleosPH1: 'Real jobs, reviewed and safe',
      empleosPLead: 'Real, verified jobs — remote and on-site. A stable income helps a family rebuild its stability.',
      empleosNoticeT: 'Before you apply', empleosNoticeX: 'Opportunities are curated and verified manually. Even so, we recommend confirming each offer before sharing personal information.',
      fTodas: 'All', fRemoto: 'Remote', fPresencial: 'On-site', fHibrido: 'Hybrid',
      empleosEmpty: 'No jobs with this work mode. Try another.',
      ofertaVerificada: 'Verified job',
      orgsPEyebrow: 'Organizations', orgsPH1: 'The network that makes the bridge possible',
      orgsPLead: 'Foundations, aid centers, shelters and volunteer networks. They verify cases and ensure help arrives through trusted channels.',
      areasApoyo: 'Areas of support', escribir: 'Email', contactar: 'Contact', sitioWeb: 'Website',
      allyLabel: 'Partner organization', orgPendiente: 'In review',
      sumarseT: 'Want your organization to join?', sumarseX: 'If you are a foundation, shelter or volunteer network and want to verify cases or channel help, connect with us.', sumarseBtn: 'Connect organization',
      cdEstado: 'Status', cdUbicacion: 'Location', cdActualizacion: 'Last update',
      cdResumen: 'Summary', cdNecesidades: 'Needs', cdHabilidades: 'Work skills', cdDisp: 'Work availability',
      cdNotaT: 'Safety note', cdNotaX: 'This platform does not store personal documents or process payments. Verification happens through partner organizations or volunteers.',
      cdComoApoyar: 'How to support', cdContactoSeguro: 'Safe contact',
      cdApoyar: 'Support this case', cdNoSupport: 'The support channel is enabled once verification with the partner organization is complete.', cdRecruiter: 'Are you a recruiter? View profiles',
      volverCasos: 'Back to cases', volverEmpleos: 'Back to jobs',
      edEmpresa: 'Company', edModalidad: 'Work mode', edCategoria: 'Category', edPublicado: 'Posted',
      edDescripcion: 'Description', edRequisitos: 'Requirements', edDetalles: 'Details',
      edAntesT: 'Before sharing your data', edAntesX: 'Opportunities are curated and verified manually. Even so, we recommend confirming each offer before sharing personal information.',
      edAplicar: 'Apply', edFuente: 'Source', edAplicarBtn: 'Apply on external site', edVerif: 'Job verified by the team',
      comoEyebrow: 'The model', comoH1: 'How it works',
      comoLead: 'We are a public connection layer, not a donation app or a financial intermediary. These are the principles guiding every decision.',
      cf1T: 'The platform centralizes safe information', cf1X: 'We gather cases, remote and on-site jobs, and partner organizations in one place. All information is public and safe: never IDs, passports or private documents.',
      cf2T: 'Cases come from partner organizations', cf2X: 'We do not publish cases on our own. Each family or person is identified and verified by a partner foundation, shelter or volunteer network.',
      cf3T: 'No sensitive documents are stored', cf3X: 'There is no personal database or login. Contact and verification happen through the organizations’ channels, not on this site.',
      cf4T: 'No payments are processed', cf4X: 'The platform does not receive or manage money. Donations and support flow directly through each organization’s verified channels.',
      cf5T: 'Opportunities are curated and verified', cf5X: 'No scraping. Each remote or on-site job is reviewed and verified manually before publishing.',
      cf6T: 'We connect immediate help with stability', cf6X: 'The end goal: that one-off help solves the present and a job rebuilds financial stability for the long term.',
      limEyebrow: 'Clear limits', limH2: 'What we do and do not do',
      siT: 'What we DO', si1: 'Publish verified cases with public information.', si2: 'Manually curate and verify remote and on-site jobs.', si3: 'Connect families with organizations, donors and recruiters.', si4: 'Keep everything static, safe and simple.',
      noT: 'What we DO NOT do', no1: 'Process payments or donations on the platform.', no2: 'Store IDs, passports or private documents.', no3: 'Require login or create accounts.', no4: 'Scrape LinkedIn, Indeed or other platforms.',
      compT: 'Commitment to safety and dignity', compX: 'This platform does not store personal documents or process payments. Verification happens through partner organizations or volunteers. Every case is treated with respect: we seek not charity, but connection, stability and dignity.',
      comoCtaEyebrow: 'Take part', comoCtaH2: 'Help turn the present into stability', comoCtaX: 'Post a job, connect your organization or share a verified case. Every connection counts.', comoCtaB1: 'Post a job', comoCtaB2: 'View cases',
      pubEyebrow: 'For recruiters and anyone', pubH1: 'Post a verified job',
      pubLead: 'Recruiters, companies and allies can post jobs —remote or on-site—. We review and verify every submission manually before publishing.',
      pubJobT: 'Job details', pubJobSub: 'No servers or database: we receive your submission and our team verifies it manually before publishing.',
      pubSentT: 'Thank you! We received your submission', pubSentX: 'We will review and verify it. If it is a real, safe offer, we will publish it as a verified job.',
      lTitulo: 'Job title', lEmpresa: 'Company', lModalidad: 'Work mode', lUbicacion: 'Location (if on-site)', lCategoria: 'Category', lDescripcion: 'Role description', lLink: 'Link or email to apply', lCorreo: 'Your contact email',
      phTitulo: 'e.g. Administrative assistant', phEmpresa: 'Your company or organization name', phUbicacion: 'e.g. La Guaira, Venezuela', phCategoria: 'e.g. Technology, Logistics, Design', phDescripcion: 'Responsibilities, key requirements and what the company offers', phCorreo: 'you@company.com',
      optRemoto: 'Remote', optPresencial: 'On-site', optHibrido: 'Hybrid',
      pubJobBtn: 'Submit job',
      pubOrgT: 'Connect an organization', pubOrgSub: 'Are you a foundation, shelter, aid center or volunteer network? Join as an ally to verify cases and channel help.',
      pubOrgSentT: 'Request received!', pubOrgSentX: 'We will contact you to add your organization to the ally network.',
      lOrgNombre: 'Organization name', lOrgTipo: 'Type', lOrgAreas: 'Areas of support', lOrgContacto: 'Email or contact channel',
      phOrgTipo: 'Foundation, shelter, aid center…', phOrgAreas: 'Verification, food, mentoring…', phOrgContacto: 'contact@organization.org',
      pubOrgBtn: 'Send partnership request',
      curamosT: 'How we verify', cur1: 'We receive your submission.', cur2: 'We verify it is a real, safe offer.', cur3: 'We publish it as a verified job.', cur4: 'We connect it with relevant profiles.',
      sinBackT: 'No backend, no sensitive data', sinBackX: 'We do not store information on servers or process payments.',
      escribeDirecto: 'Prefer to write directly?',
      reqAll: 'required',
      navRegistro: 'Register',
      regEyebrow: 'Join Donde Ayudar', regH1: 'Create your account',
      regLead: 'Donde Ayudar is for everyone. Join as a recruiter or company, as a partner organization or as a volunteer: post opportunities, verify cases or support families. We rebuild together.',
      regTabRecruiter: 'I am a recruiter / company', regTabOrg: 'I am a partner organization', regTabPersona: 'I am a volunteer / individual',
      regRecDesc: 'Post remote and on-site jobs, verified by the team.',
      regOrgDesc: 'Verify cases, support families and channel help through safe channels.',
      regPersonaDesc: 'Share opportunities, spread verified cases and support affected families. Anyone can pitch in.',
      regNombre: 'Full name', regEmail: 'Email', regEntidad: 'Company or organization (if any)',
      regPass: 'Password', regPass2: 'Confirm password',
      regBtn: 'Create account', regSentT: 'Account created!',
      regSentX: 'Demo without backend: no credentials or data are stored. You can now post a job or connect your organization.',
      regHave: 'Already have an account?', regLogin: 'Sign in',
      regNote: 'Demo platform: registration is visual and stores no data or passwords.',
      regGoPublicar: 'Post a job', regGoOrg: 'Connect organization', regGoCasos: 'Explore cases',
    },
  };

  const CASOS = [
    {
      id: 'familia-rojas-maiquetia', status: 'verified', date: '2026-06-20', supportLink: '#',
      title: { es: 'Familia Rojas — Maiquetía', en: 'Rojas Family — Maiquetía' },
      location: { es: 'Maiquetía, La Guaira', en: 'Maiquetía, La Guaira' },
      verifiedBy: { es: 'Fundación Manos del Litoral', en: 'Manos del Litoral Foundation' },
      dateLabel: { es: '20 de junio de 2026', en: 'June 20, 2026' },
      summary: { es: 'Madre y dos hijos perdieron su vivienda por las lluvias. Buscan estabilidad mientras reconstruyen; la madre tiene experiencia en atención al cliente y redes sociales.', en: 'A mother and two children lost their home to the floods. They seek stability while rebuilding; the mother has experience in customer service and social media.' },
      needs: { es: ['Empleo remoto estable', 'Mercados de alimentos (1 mes)', 'Útiles escolares'], en: ['Stable remote job', 'Food supplies (1 month)', 'School supplies'] },
      skills: { es: ['Atención al cliente', 'Community management', 'Excel intermedio'], en: ['Customer service', 'Community management', 'Intermediate Excel'] },
      remoteWorkAvailability: { es: 'Tiempo completo, horario flexible, equipo propio disponible', en: 'Full-time, flexible hours, own equipment available' },
      contactMethod: { es: 'A través de Fundación Manos del Litoral (canal verificado)', en: 'Through Manos del Litoral Foundation (verified channel)' },
      donationMethods: [
        { type: 'zelle', label: 'Zelle', holder: 'Ana Rojas', value: 'ana.rojas.ayuda@gmail.com', note: { es: 'Donación directa a la familia', en: 'Direct donation to the family' } },
        { type: 'pago_movil', label: 'Pago Móvil', holder: 'Ana Rojas', bank: 'Banesco (0134)', phone: '0414-555-0142', idNumber: 'V-12.345.678', note: { es: 'Pago móvil nacional', en: 'National mobile payment' } },
      ],
      body: {
        es: [
          { t: 'p', text: 'La familia Rojas vivía en una zona baja de Maiquetía afectada por las crecidas. Tras perder su vivienda, fueron reubicados temporalmente con apoyo de una organización aliada.' },
          { t: 'p', text: 'Su prioridad no es la dependencia, sino la reconstrucción. La señora Rojas trabajó tres años en atención al cliente para un comercio local y maneja redes sociales. Está disponible para incorporarse de inmediato.' },
          { t: 'p', text: 'El apoyo inmediato (alimentos y útiles) cubre las próximas semanas; un empleo estable resolvería la raíz del problema.' },
        ],
        en: [
          { t: 'p', text: 'The Rojas family lived in a low-lying area of Maiquetía hit by the floods. After losing their home, they were temporarily relocated with support from a partner organization.' },
          { t: 'p', text: 'Their priority is not dependency but rebuilding. Mrs. Rojas worked three years in customer service for a local business and manages social media. She is available to start immediately.' },
          { t: 'p', text: 'Immediate help (food and supplies) covers the coming weeks; a stable job would solve the root of the problem.' },
        ],
      },
    },
    {
      id: 'maria-contadora-la-guaira', status: 'verified', date: '2026-06-18', supportLink: null,
      title: { es: 'María — Asistente contable', en: 'María — Accounting assistant' },
      location: { es: 'La Guaira (casco central)', en: 'La Guaira (downtown)' },
      verifiedBy: { es: 'Centro de Acopio San Juan', en: 'San Juan Aid Center' },
      dateLabel: { es: '18 de junio de 2026', en: 'June 18, 2026' },
      summary: { es: 'Madre cabeza de familia con experiencia administrativa y contable. Su lugar de trabajo cerró tras la emergencia; busca empleo en administración o finanzas.', en: 'Single mother with administrative and accounting experience. Her workplace closed after the emergency; she seeks a job in administration or finance.' },
      needs: { es: ['Empleo administrativo / contable', 'Apoyo en alquiler temporal'], en: ['Administrative / accounting job', 'Temporary rent support'] },
      skills: { es: ['Contabilidad básica', 'Administración', 'Facturación y cobranzas', 'Google Workspace'], en: ['Basic accounting', 'Administration', 'Billing and collections', 'Google Workspace'] },
      remoteWorkAvailability: { es: 'Medio tiempo o tiempo completo, mañanas preferiblemente', en: 'Part-time or full-time, mornings preferred' },
      contactMethod: { es: 'A través del Centro de Acopio San Juan (canal verificado)', en: 'Through San Juan Aid Center (verified channel)' },
      donationMethods: [
        { type: 'paypal', label: 'PayPal', holder: 'María González', value: 'paypal.me/mariagonzalez', note: { es: 'Apoyo directo', en: 'Direct support' } },
        { type: 'zelle', label: 'Zelle', holder: 'María González', value: 'maria.gonzalez.ayuda@gmail.com', note: { es: 'Donación directa', en: 'Direct donation' } },
      ],
      body: {
        es: [
          { t: 'p', text: 'María tiene más de cinco años de experiencia en tareas administrativas y contables. El comercio donde trabajaba cerró de forma permanente tras la emergencia.' },
          { t: 'p', text: 'Es organizada, confiable y maneja herramientas de oficina en la nube. Un puesto de administración, facturación o asistencia contable le permitiría sostener a su familia de forma autónoma.' },
        ],
        en: [
          { t: 'p', text: 'María has over five years of experience in administrative and accounting tasks. The business where she worked closed permanently after the emergency.' },
          { t: 'p', text: 'She is organized, reliable and handles cloud office tools. An administration, billing or accounting-assistant role would let her support her family independently.' },
        ],
      },
    },
    {
      id: 'carlos-desarrollador-catia-la-mar', status: 'urgent', date: '2026-06-26', supportLink: '#',
      title: { es: 'Carlos — Técnico y aspirante a desarrollador', en: 'Carlos — Technician and aspiring developer' },
      location: { es: 'Catia La Mar, La Guaira', en: 'Catia La Mar, La Guaira' },
      verifiedBy: { es: 'Voluntariado Tech Litoral', en: 'Tech Litoral Volunteers' },
      dateLabel: { es: '26 de junio de 2026', en: 'June 26, 2026' },
      summary: { es: 'Joven con formación técnica perdió su equipo de trabajo en la emergencia. Necesita reactivar ingresos con urgencia; conocimientos de soporte IT y bases de programación web.', en: 'A young man with technical training lost his work equipment in the emergency. He urgently needs to restart income; knows IT support and web programming basics.' },
      needs: { es: ['Laptop o equipo de trabajo', 'Empleo (soporte / QA / dev junior)', 'Conexión a internet estable'], en: ['Laptop or work equipment', 'Job (support / QA / junior dev)', 'Stable internet connection'] },
      skills: { es: ['Soporte técnico', 'HTML / CSS / JavaScript básico', 'Inglés intermedio'], en: ['Technical support', 'Basic HTML / CSS / JavaScript', 'Intermediate English'] },
      remoteWorkAvailability: { es: 'Inmediata, tiempo completo o medio tiempo', en: 'Immediate, full-time or part-time' },
      contactMethod: { es: 'Coordinado por Voluntariado Tech Litoral (verificado)', en: 'Coordinated by Tech Litoral Volunteers (verified)' },
      donationMethods: [
        { type: 'pago_movil', label: 'Pago Móvil', holder: 'Carlos Pérez', bank: 'Mercantil (0105)', phone: '0412-555-0173', idNumber: 'V-20.111.222', note: { es: 'Para reponer su equipo de trabajo', en: 'To replace his work equipment' } },
        { type: 'bank_of_america', label: 'Bank of America', holder: 'Carlos Pérez', value: 'Compartido con consentimiento del beneficiario', note: { es: 'Transferencia directa', en: 'Direct transfer' } },
      ],
      body: {
        es: [
          { t: 'p', text: 'Carlos estudiaba de forma autodidacta y hacía soporte técnico independiente cuando la emergencia lo dejó sin su equipo de trabajo, su principal herramienta de ingreso.' },
          { t: 'p', text: 'Tiene bases sólidas de soporte IT y está completando fundamentos de desarrollo web. Con un equipo y una oportunidad de entrada puede volver a generar ingresos de inmediato.' },
          { t: 'quote', text: 'Este es un caso urgente: la prioridad es reactivar la capacidad de trabajar.' },
        ],
        en: [
          { t: 'p', text: 'Carlos was studying on his own and doing freelance technical support when the emergency left him without his work equipment, his main source of income.' },
          { t: 'p', text: 'He has solid IT-support fundamentals and is completing web-development basics. With equipment and an entry-level opportunity he can generate income again right away.' },
          { t: 'quote', text: 'This is an urgent case: the priority is to restore the ability to work.' },
        ],
      },
    },
    {
      id: 'jose-disenador-naiguata', status: 'pending', date: '2026-06-28', supportLink: null,
      title: { es: 'José — Diseñador gráfico', en: 'José — Graphic designer' },
      location: { es: 'Naiguatá, La Guaira', en: 'Naiguatá, La Guaira' },
      verifiedBy: { es: 'Red de Voluntarios Costa Arriba', en: 'Costa Arriba Volunteer Network' },
      dateLabel: { es: '28 de junio de 2026', en: 'June 28, 2026' },
      summary: { es: 'Diseñador gráfico con portafolio en identidad visual y redes. En proceso de verificación; busca clientes o empleo part-time para estabilizar ingresos.', en: 'Graphic designer with a portfolio in visual identity and social media. In the verification process; seeks clients or a part-time job to stabilize income.' },
      needs: { es: ['Clientes / empleo de diseño', 'Restablecer conexión a internet'], en: ['Clients / design job', 'Restore internet connection'] },
      skills: { es: ['Diseño gráfico', 'Identidad visual / branding', 'Figma e Illustrator', 'Diseño para redes sociales'], en: ['Graphic design', 'Visual identity / branding', 'Figma and Illustrator', 'Social media design'] },
      remoteWorkAvailability: { es: 'Part-time, proyectos freelance o medio tiempo', en: 'Part-time, freelance projects or half-time' },
      contactMethod: { es: 'En verificación con Red de Voluntarios Costa Arriba', en: 'In verification with Costa Arriba Volunteer Network' },
      body: {
        es: [
          { t: 'p', text: 'José trabaja como diseñador gráfico independiente. La interrupción de servicios en su zona afectó su capacidad de atender clientes y mantener ingresos estables.' },
          { t: 'p', text: 'Su caso está en proceso de verificación por la organización aliada. Una vez confirmado, se habilitará el canal seguro de contacto. Mientras tanto, su perfil sirve para que empresas y recruiters interesados puedan expresar interés.' },
        ],
        en: [
          { t: 'p', text: 'José works as a freelance graphic designer. The disruption of services in his area affected his ability to serve clients and maintain stable income.' },
          { t: 'p', text: 'His case is in the verification process with the partner organization. Once confirmed, the safe contact channel will be enabled. Meanwhile, his profile lets interested companies and recruiters express interest.' },
        ],
      },
    },
  ];

  const EMPLEOS = [
    {
      id: 'desarrollador-frontend-junior', company: 'Lumo Studio', mode: 'remoto', date: '2026-06-25', applyUrl: '#', verified: true,
      title: { es: 'Desarrollador/a Frontend Junior', en: 'Junior Frontend Developer' },
      place: { es: '100% remoto', en: '100% remote' },
      category: { es: 'Tecnología', en: 'Technology' },
      dateLabel: { es: '25 de junio de 2026', en: 'June 25, 2026' },
      source: { es: 'Curado manualmente — bolsa de empleo de Lumo Studio', en: 'Manually curated — Lumo Studio job board' },
      description: { es: 'Estudio de producto busca desarrollador frontend junior para construir interfaces con React y CSS moderno. Mentoría semanal y proyectos reales desde el primer mes.', en: 'A product studio seeks a junior frontend developer to build interfaces with React and modern CSS. Weekly mentoring and real projects from the first month.' },
      requirements: { es: ['HTML, CSS y JavaScript sólidos', 'Nociones de React (o ganas de aprenderlo)', 'Manejo básico de Git', 'Inglés para lectura técnica'], en: ['Solid HTML, CSS and JavaScript', 'React basics (or eagerness to learn)', 'Basic Git', 'English for technical reading'] },
      tags: { es: ['React', 'Frontend', 'Junior', 'Mentoría'], en: ['React', 'Frontend', 'Junior', 'Mentoring'] },
      body: {
        es: [
          { t: 'p', text: 'Lumo Studio diseña y construye productos digitales para clientes de Norteamérica. Buscan una persona junior con bases técnicas y muchas ganas de crecer.' },
          { t: 'h', text: 'Stack y dinámica' },
          { t: 'ul', items: ['React + CSS moderno.', 'Code reviews y mentoría semanal.', 'Proyectos reales desde la cuarta semana.'] },
        ],
        en: [
          { t: 'p', text: 'Lumo Studio designs and builds digital products for North American clients. They seek a junior person with technical fundamentals and eagerness to grow.' },
          { t: 'h', text: 'Stack and dynamics' },
          { t: 'ul', items: ['React + modern CSS.', 'Code reviews and weekly mentoring.', 'Real projects from week four.'] },
        ],
      },
    },
    {
      id: 'agente-soporte-cliente-bilingue', company: 'NimbusCare', mode: 'remoto', date: '2026-06-22', applyUrl: '#', verified: true,
      title: { es: 'Agente de Soporte al Cliente (Bilingüe)', en: 'Customer Support Agent (Bilingual)' },
      place: { es: 'Remoto · LatAm', en: 'Remote · LatAm' },
      category: { es: 'Atención al cliente', en: 'Customer service' },
      dateLabel: { es: '22 de junio de 2026', en: 'June 22, 2026' },
      source: { es: 'Curado manualmente — contacto directo con RRHH de NimbusCare', en: 'Manually curated — direct contact with NimbusCare HR' },
      description: { es: 'Empresa de software busca agentes de soporte para atender clientes por chat y correo. Horarios rotativos, capacitación pagada y equipo de trabajo provisto tras el primer mes.', en: 'A software company seeks support agents to assist customers via chat and email. Rotating shifts, paid training and work equipment provided after the first month.' },
      requirements: { es: ['Español nativo e inglés intermedio (B2)', 'Experiencia en atención al cliente (1+ año)', 'Conexión a internet estable', 'Disponibilidad de tiempo completo'], en: ['Native Spanish and intermediate English (B2)', 'Customer service experience (1+ year)', 'Stable internet connection', 'Full-time availability'] },
      tags: { es: ['Soporte', 'Bilingüe', 'Full-time', 'Capacitación incluida'], en: ['Support', 'Bilingual', 'Full-time', 'Training included'] },
      body: {
        es: [
          { t: 'p', text: 'NimbusCare es una empresa de software B2B que está expandiendo su equipo de soporte para LatAm. Buscan personas empáticas y resolutivas para atención por chat y correo.' },
          { t: 'h', text: 'Lo que ofrecen' },
          { t: 'ul', items: ['Salario competitivo en USD.', 'Capacitación pagada de dos semanas.', 'Equipo de trabajo provisto luego del primer mes.', 'Horarios rotativos con días libres consecutivos.'] },
        ],
        en: [
          { t: 'p', text: 'NimbusCare is a B2B software company expanding its support team for LatAm. They seek empathetic, resourceful people for chat and email assistance.' },
          { t: 'h', text: 'What they offer' },
          { t: 'ul', items: ['Competitive salary in USD.', 'Two weeks of paid training.', 'Work equipment provided after the first month.', 'Rotating shifts with consecutive days off.'] },
        ],
      },
    },
    {
      id: 'asistente-administrativo-virtual', company: 'Helbridge Consulting', mode: 'remoto', date: '2026-06-19', applyUrl: '#', verified: true,
      title: { es: 'Asistente Administrativo Virtual', en: 'Virtual Administrative Assistant' },
      place: { es: 'Remoto · global', en: 'Remote · global' },
      category: { es: 'Administración', en: 'Administration' },
      dateLabel: { es: '19 de junio de 2026', en: 'June 19, 2026' },
      source: { es: 'Curado manualmente — referido por organización aliada', en: 'Manually curated — referred by a partner organization' },
      description: { es: 'Consultora busca asistente virtual para gestión de agenda, facturación, seguimiento de clientes y tareas administrativas. Trabajo por objetivos con horario flexible.', en: 'A consultancy seeks a virtual assistant for scheduling, billing, client follow-up and administrative tasks. Goal-based work with flexible hours.' },
      requirements: { es: ['Experiencia administrativa o contable', 'Organización y atención al detalle', 'Google Workspace y hojas de cálculo', 'Comunicación clara por escrito'], en: ['Administrative or accounting experience', 'Organization and attention to detail', 'Google Workspace and spreadsheets', 'Clear written communication'] },
      tags: { es: ['Administración', 'Asistente virtual', 'Horario flexible', 'Part-time'], en: ['Administration', 'Virtual assistant', 'Flexible hours', 'Part-time'] },
      body: {
        es: [
          { t: 'p', text: 'Helbridge Consulting apoya a pequeñas empresas con servicios administrativos. Buscan una persona ordenada y confiable para tareas de back-office.' },
          { t: 'h', text: 'Responsabilidades' },
          { t: 'ul', items: ['Gestión de agenda y correos.', 'Facturación y seguimiento de cobranzas.', 'Organización de documentos y reportes simples.'] },
        ],
        en: [
          { t: 'p', text: 'Helbridge Consulting supports small businesses with administrative services. They seek an organized, reliable person for back-office tasks.' },
          { t: 'h', text: 'Responsibilities' },
          { t: 'ul', items: ['Scheduling and email management.', 'Billing and collections follow-up.', 'Document organization and simple reports.'] },
        ],
      },
    },
    {
      id: 'disenador-redes-sociales', company: 'Marca Viva', mode: 'remoto', date: '2026-06-27', applyUrl: '#', verified: true,
      title: { es: 'Diseñador/a de Contenido para Redes', en: 'Social Media Content Designer' },
      place: { es: 'Remoto · LatAm', en: 'Remote · LatAm' },
      category: { es: 'Diseño', en: 'Design' },
      dateLabel: { es: '27 de junio de 2026', en: 'June 27, 2026' },
      source: { es: 'Curado manualmente — bolsa de talento de Marca Viva', en: 'Manually curated — Marca Viva talent pool' },
      description: { es: 'Agencia de marketing busca diseñador para crear piezas gráficas y plantillas para redes sociales de varios clientes. Portafolio requerido; freelance con posibilidad de fijo.', en: 'A marketing agency seeks a designer to create graphics and templates for several clients’ social media. Portfolio required; freelance with potential for a permanent role.' },
      requirements: { es: ['Dominio de Figma, Canva o Illustrator', 'Portafolio de piezas para redes', 'Manejo de tiempos y entregas', 'Creatividad y consistencia de marca'], en: ['Proficiency in Figma, Canva or Illustrator', 'Portfolio of social media pieces', 'Deadline management', 'Creativity and brand consistency'] },
      tags: { es: ['Diseño', 'Redes sociales', 'Freelance', 'Portafolio'], en: ['Design', 'Social media', 'Freelance', 'Portfolio'] },
      body: {
        es: [
          { t: 'p', text: 'Marca Viva gestiona redes sociales para marcas de consumo en LatAm. Necesitan a alguien creativo para producir piezas gráficas y mantener la coherencia visual.' },
          { t: 'h', text: 'Modalidad' },
          { t: 'ul', items: ['Inicio como freelance por proyecto.', 'Posibilidad de pasar a colaboración fija según desempeño.', 'Pagos quincenales.'] },
        ],
        en: [
          { t: 'p', text: 'Marca Viva manages social media for consumer brands in LatAm. They need someone creative to produce graphics and maintain visual consistency.' },
          { t: 'h', text: 'Arrangement' },
          { t: 'ul', items: ['Start as a freelancer per project.', 'Possibility of a permanent role based on performance.', 'Bi-weekly payments.'] },
        ],
      },
    },
    {
      id: 'asistente-logistica-acopio', company: 'Centro de Acopio San Juan', mode: 'presencial', date: '2026-06-24', applyUrl: '#', verified: true,
      title: { es: 'Asistente de Logística (Centro de Acopio)', en: 'Logistics Assistant (Aid Center)' },
      place: { es: 'La Guaira (casco central)', en: 'La Guaira (downtown)' },
      category: { es: 'Logística', en: 'Logistics' },
      dateLabel: { es: '24 de junio de 2026', en: 'June 24, 2026' },
      source: { es: 'Verificado — vacante directa del Centro de Acopio San Juan', en: 'Verified — direct vacancy from San Juan Aid Center' },
      description: { es: 'Vacante presencial para apoyar la recepción, organización y distribución de insumos en el centro de acopio. Ideal para personas de la zona que buscan ingreso estable y cercano.', en: 'On-site role to support intake, organization and distribution of supplies at the aid center. Ideal for local people seeking a stable, nearby income.' },
      requirements: { es: ['Disponibilidad presencial en La Guaira', 'Orden y trabajo en equipo', 'Capacidad para tareas físicas ligeras', 'Compromiso y puntualidad'], en: ['On-site availability in La Guaira', 'Organization and teamwork', 'Ability for light physical tasks', 'Commitment and punctuality'] },
      tags: { es: ['Presencial', 'Logística', 'La Guaira', 'Ingreso estable'], en: ['On-site', 'Logistics', 'La Guaira', 'Stable income'] },
      body: {
        es: [
          { t: 'p', text: 'El Centro de Acopio San Juan amplía su equipo presencial para gestionar el flujo de donaciones e insumos hacia las familias afectadas.' },
          { t: 'h', text: 'Tareas' },
          { t: 'ul', items: ['Recepción y clasificación de insumos.', 'Apoyo en la distribución a familias.', 'Registro simple de entradas y salidas.'] },
        ],
        en: [
          { t: 'p', text: 'San Juan Aid Center is expanding its on-site team to manage the flow of donations and supplies to affected families.' },
          { t: 'h', text: 'Tasks' },
          { t: 'ul', items: ['Intake and sorting of supplies.', 'Support in distribution to families.', 'Simple logging of items in and out.'] },
        ],
      },
    },
    {
      id: 'coordinador-programas-comunitarios', company: 'Fundación Manos del Litoral', mode: 'hibrido', date: '2026-06-23', applyUrl: '#', verified: true,
      title: { es: 'Coordinador/a de Programas Comunitarios', en: 'Community Programs Coordinator' },
      place: { es: 'Maiquetía · híbrido', en: 'Maiquetía · hybrid' },
      category: { es: 'Social', en: 'Community' },
      dateLabel: { es: '23 de junio de 2026', en: 'June 23, 2026' },
      source: { es: 'Verificado — vacante directa de Fundación Manos del Litoral', en: 'Verified — direct vacancy from Manos del Litoral Foundation' },
      description: { es: 'Rol híbrido para coordinar programas de apoyo a familias: visitas en terreno y trabajo remoto de seguimiento. Perfil organizado con sensibilidad social.', en: 'Hybrid role to coordinate family support programs: field visits and remote follow-up work. Organized profile with social sensitivity.' },
      requirements: { es: ['Experiencia en trabajo comunitario o social', 'Disponibilidad para visitas en Maiquetía', 'Organización y reportería', 'Buena comunicación'], en: ['Experience in community or social work', 'Availability for visits in Maiquetía', 'Organization and reporting', 'Good communication'] },
      tags: { es: ['Híbrido', 'Social', 'Maiquetía', 'Coordinación'], en: ['Hybrid', 'Community', 'Maiquetía', 'Coordination'] },
      body: {
        es: [
          { t: 'p', text: 'Manos del Litoral busca una persona para coordinar sus programas de acompañamiento a familias afectadas, combinando terreno y seguimiento remoto.' },
          { t: 'h', text: 'Responsabilidades' },
          { t: 'ul', items: ['Visitas y acompañamiento en terreno.', 'Seguimiento remoto y reportería.', 'Coordinación con voluntarios y aliados.'] },
        ],
        en: [
          { t: 'p', text: 'Manos del Litoral seeks a person to coordinate its family support programs, combining fieldwork and remote follow-up.' },
          { t: 'h', text: 'Responsibilities' },
          { t: 'ul', items: ['Field visits and accompaniment.', 'Remote follow-up and reporting.', 'Coordination with volunteers and allies.'] },
        ],
      },
    },
  ];

  const ORGS = [
    {
      id: 'fundacion-manos-del-litoral', verified: true, contact: 'contacto@manosdellitoral.example', website: '#',
      title: { es: 'Fundación Manos del Litoral', en: 'Manos del Litoral Foundation' },
      type: { es: 'Fundación / Verificador', en: 'Foundation / Verifier' },
      location: { es: 'Maiquetía, La Guaira', en: 'Maiquetía, La Guaira' },
      description: { es: 'Organización comunitaria que acompaña a familias afectadas, verifica casos y coordina apoyo inmediato con voluntarios locales.', en: 'Community organization that accompanies affected families, verifies cases and coordinates immediate support with local volunteers.' },
      areas: { es: ['Verificación de casos', 'Acompañamiento a familias', 'Coordinación de voluntarios'], en: ['Case verification', 'Family accompaniment', 'Volunteer coordination'] },
    },
    {
      id: 'voluntariado-tech-litoral', verified: true, contact: 'tech@litoral.example', website: '#',
      title: { es: 'Voluntariado Tech Litoral', en: 'Tech Litoral Volunteers' },
      type: { es: 'Red de voluntarios', en: 'Volunteer network' },
      location: { es: 'Catia La Mar, La Guaira', en: 'Catia La Mar, La Guaira' },
      description: { es: 'Grupo de profesionales tech que mentorean, verifican perfiles laborales y conectan a personas con habilidades digitales con oportunidades remotas.', en: 'A group of tech professionals who mentor, verify work profiles and connect people with digital skills to remote opportunities.' },
      areas: { es: ['Mentoría técnica', 'Verificación de perfiles laborales', 'Conexión con recruiters'], en: ['Technical mentoring', 'Work profile verification', 'Recruiter connections'] },
    },
    {
      id: 'centro-acopio-san-juan', verified: true, contact: 'https://wa.me/000000000', website: null,
      title: { es: 'Centro de Acopio San Juan', en: 'San Juan Aid Center' },
      type: { es: 'Centro de acopio', en: 'Aid center' },
      location: { es: 'La Guaira (casco central)', en: 'La Guaira (downtown)' },
      description: { es: 'Punto de recolección y distribución de alimentos, ropa e insumos básicos para familias afectadas. También canaliza casos hacia la plataforma.', en: 'Collection and distribution point for food, clothing and basic supplies for affected families. It also channels cases to the platform.' },
      areas: { es: ['Alimentos e insumos', 'Distribución logística', 'Recepción de casos'], en: ['Food and supplies', 'Logistics distribution', 'Case intake'] },
    },
    {
      id: 'refugio-costa-arriba', verified: false, contact: 'refugio@costaarriba.example', website: null,
      title: { es: 'Refugio Costa Arriba', en: 'Costa Arriba Shelter' },
      type: { es: 'Refugio temporal', en: 'Temporary shelter' },
      location: { es: 'Naiguatá, La Guaira', en: 'Naiguatá, La Guaira' },
      description: { es: 'Espacio de alojamiento temporal y apoyo psicosocial para familias desplazadas por la emergencia en la zona de Costa Arriba.', en: 'Temporary housing and psychosocial support for families displaced by the emergency in the Costa Arriba area.' },
      areas: { es: ['Alojamiento temporal', 'Apoyo psicosocial', 'Alimentación'], en: ['Temporary housing', 'Psychosocial support', 'Food'] },
    },
  ];

  return { STRINGS: STRINGS, CASOS: CASOS, EMPLEOS: EMPLEOS, ORGS: ORGS };
})();